### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Dimanteo** [quaiion/differentiator#1]
* https://github.com/quaiion/differentiator/blob/3c48bab4290bec4bf53331a768a2f304a1db74f2/diftor.cpp#L53-L61
Здесь можно сделать `else`

* https://github.com/quaiion/differentiator/blob/3c48bab4290bec4bf53331a768a2f304a1db74f2/diftor.cpp#L3-L13
Вообще говоря, `return` внутри дефайна очень опасная практика. Лучше логику вынести все-таки в функцию, которая будет возвращать результат проверки. А уже печать сообщения об ошибке сделать дефайном (чтобы __FUNC__ и прочие работали). Это же касается и дефайна `TREE_COLLAPSE`. Если говорить более общо - **не надо писать дефайны, которые могут влиять на поток управления программы.**
```C
// Пример как можно сделать
if (!func, security(id, node, cond)) {
    PRINT_ERROR(...)
    return NULL
]
```

* https://github.com/quaiion/differentiator/blob/3c48bab4290bec4bf53331a768a2f304a1db74f2/diftor.cpp#L693-L706
Можно. Код в них вроде абсолютно идентичный.
```C
case PLUS:
case MINUS:
{...}
```

* Проект не компилится на линуксе, потому что ему не хватает объявлений `system()` и `atoll()`. Чтобы это пофиксить добавь в common.hpp заголовок `#include <stdlib.h>`. Это на будущее, когда кто-нибудь (ты) захочет собрать эьто под линуксом

* Добавь в репозиторий пример входных данных и выходных данных. И напиши, пожалуйста, небольшую readme, о том в каком формате и что можно вводить. Я в целом могу угадать формат входных данных по коду твоего рекурсивного спуска, но это не юзер-френдли))

**Comment by quaiion** [comment]
Закрыто коммитом "Исправление ошибок первой версии"
